server.port=8082

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/qatra}
spring.datasource.username=${DB_USERNAME:qatra}
spring.datasource.password=${DB_PASSWORD:qatra}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

notification.channels=${NOTIFICATION_CHANNELS:IN_APP,EMAIL}

email.channel.provider=${EMAIL_CHANNEL_PROVIDER:sendgrid}
