spring.application.name=Qatra

spring.threads.virtual.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/qatra
spring.datasource.username=qatra
spring.datasource.password=qatra
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.minimum-idle=2

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Actuator
management.endpoints.web.exposure.include=health,info,modules
management.endpoint.health.show-details=always

# Spring Modulith
spring.modulith.detection.base-packages=com.zayenha
spring.modulith.runtime.verification-enabled=true

# DevTools
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# Modulith Observability
spring.modulith.observability.events.enabled=true
