spring.datasource.url=jdbc:postgresql://localhost:5432/qatra_dev
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
# DevTools
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
