spring.application.name=Qatra

# Actuator
management.endpoints.web.exposure.include=health,info,modules
management.endpoint.health.show-details=always

# Spring Modulith
spring.modulith.detection.base-packages=com.zayenha

# DevTools
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# Modulith Observability
spring.modulith.observability.events.enabled=true
